[*]
ctx-size = 65535
batch-size = 4096
ubatch-size = 2048
gpu-layers = 99
flash-attn = on
temp = 0.7
top-k = 40
top-p = 0.95
min-p = 0.01
no-ui = true
mmap = false
mlock = true
models-autoload = true
jinja = true
cache-reuse = 256
parallel = 1
poll = 100
poll-batch = 1
presence-penalty = 0.0
repeat-penalty = 1.0
sleep-idle-seconds = 14400
# 4h sleep = 14400 seconds

[qwen3.6-28B-REAP20-a3b]
model = /models/Qwen3.6-28B-REAP20-A3B-Q4_K_M.gguf      
ctx-size = 131070
n-cpu-moe = 17
cache-type-k = turbo4
cache-type-v = turbo2
batch-size = 2048
ubatch-size = 1024
threads = 19

# GLM-4.7-Flash-23B-A3B-Q4_M.gguf  
# GLM-4.7-Flash-Q4_K_M.gguf  
# Qwen3.6-35B-A3B-MXFP4_MOE.gguf  
# gemma-4-E4B-it-Q8_0.gguf
# Qwen3.6-28B-REAP20-A3B-Q4_K_M.gguf      
# gemma-4-26B-A4B-it-MXFP4_MOE.gguf

# Qwopus3.6-35B-A3B-v1-Q4_K_M.gguf

[Qwopus3.6-35B-A3B]
model = /models/Qwopus3.6-35B-A3B-v1-Q4_K_M.gguf
ctx-size = 131070
n-cpu-moe = 26
cache-type-k = q8_0
cache-type-v = q8_0
#cache-type-k = turbo4
#cache-type-v = turbo2
#temp = 0.3 # good for coding but tends to loop
repeat-penalty = 1.1
threads = 19

[Qwopus3.6-35B-A3B-MTP]
model = /models/Qwopus3.6-35B-A3B-Coder-MTP-Q4_K_M.gguf
ctx-size = 131070
n-cpu-moe = 29
#cache-type-k = q8_0
#cache-type-v = q8_0
#temp = 0.3 # good for coding but tends to loop
repeat-penalty = 1.1
threads = 19
cache-type-k-draft = q8_0
cache-type-v-draft = q8_0
batch-size = 2048
ubatch-size = 1024
spec-type = draft-mtp
spec-draft-n-max = 3
spec-draft-p-min = 0.75
n-predict = 32000
spec-draft-poll = 1
spec-draft-poll-batch = 1

[GLM-4.7-Flash-Q4_K_M]
model = /models/GLM-4.7-Flash-Q4_K_M.gguf
ctx-size = 131070
n-cpu-moe = 28
cache-type-k = q4_0
cache-type-v = q4_0
threads = 19

[gemma4-26b-a4b-mxfp4]
model = /models/gemma-4-26B-A4B-it-MXFP4_MOE.gguf
ctx-size = 131070
n-cpu-moe = 17
cache-type-k = q8_0
cache-type-v = q8_0

[Ornith1.0-35b-moe]
model = /models/ornith-1.0-35b-Q4_K_M.gguf
ctx-size = 131070
n-cpu-moe = 25
cache-type-k = q8_0
cache-type-v = q8_0
#cache-type-k = turbo4
#cache-type-v = turbo2
temp = 0.3
threads = 19

[qwen3.6-35b-a3b-mtp]
model = /models/Qwen3.6-35B-A3B-MXFP4_MOE.gguf
ctx-size = 131070
n-cpu-moe = 28
#cache-type-k = turbo4
#cache-type-v = turbo2
cache-type-k = q8_0
cache-type-v = q8_0
cache-type-k-draft = q8_0
cache-type-v-draft = q8_0
#cache-type-k-draft = turbo4
#cache-type-v-draft = turbo2
batch-size = 2048
ubatch-size = 1024
threads = 19
#threads = 3
spec-type = draft-mtp
spec-draft-n-max = 3
spec-draft-p-min = 0.75
n-predict = 32000
#cache-reuse = 256
spec-draft-poll = 1
spec-draft-poll-batch = 1
#presence-penalty = 0.0
#repeat-penalty = 1.0

[gemma4-e2b]
model = /models/google_gemma-4-E2B-it-IQ4_XS.gguf
ctx-size = 16384
